name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Build App Project
        run: |
          # Lưu tạm file main và pubspec
          mkdir -p backup
          cp lib/main.dart backup/main.dart
          cp pubspec.yaml backup/pubspec.yaml

          # Tạo khung Android sạch
          rm -rf .github lib pubspec.yaml
          flutter create . --org com.example.doveso --platforms android

          # Phôi phục lại file code và file pubspec
          cp backup/main.dart lib/main.dart
          cp backup/pubspec.yaml pubspec.yaml

          # Sửa minSdkVersion lên 21 & cấp quyền Camera
          sed -i 's/minSdkVersion .*/minSdkVersion 21/g' android/app/build.gradle
          sed -i '/<application/i \    <uses-permission android:name="android.permission.CAMERA"/>\n    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-DoVeSo-Release
          path: build/app/outputs/flutter-apk/app-release.apk
